CREATE TABLE `trade_executions` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`orderId` varchar(255),
	`symbol` varchar(50) NOT NULL,
	`side` enum('buy','sell') NOT NULL,
	`type` enum('market','limit','stop_loss','take_profit') NOT NULL,
	`amount` varchar(50) NOT NULL,
	`price` varchar(50),
	`stopLoss` varchar(50),
	`takeProfit` varchar(50),
	`leverage` int,
	`marginMode` enum('isolated','cross'),
	`status` enum('pending','filled','partially_filled','canceled','failed') NOT NULL,
	`filledAmount` varchar(50),
	`averagePrice` varchar(50),
	`fee` varchar(50),
	`pnl` varchar(50),
	`pnlPercent` varchar(50),
	`strategyUsed` text,
	`aiRecommendation` text,
	`errorMessage` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	`closedAt` timestamp,
	CONSTRAINT `trade_executions_id` PRIMARY KEY(`id`)
);
